
###

GET http://localhost:3022/ HTTP/1.1

###

POST http://localhost:3022/register HTTP/1.1
content-type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "am@gmail.com",
    "password": "am123"
}